### ISSUE TITLE
build/out/minit.tar.xz is missed

### ISSUE THREAD

**Issue by cloudtrends** [mesalock-linux/mesalock-distro#1]
$ ./mesalockiso 
[+] mesalockiso: installing bootloader and kernel
[+] mesalockiso: installing rootfs
tar (child): build/out/minit.tar.xz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

=======

I am build mesalock-linux on ubuntu 17.04 , and follow the instructions step by step in readme file .

thanks in advance

**Comment by mssun** [comment]
Thanks for the report. It seems that build script of `minit` breaks. I am fixing it right now.

**Comment by mssun** [comment]
The issue should be fixed in this commit: https://github.com/mesalock-linux/packages/commit/98cc80a2cefd7e7e1d40ff28dcd4aeba42256273. Can you pull the latest `mesalock-distro` and its submodule and try again? Thanks.

**Comment by cloudtrends** [comment]
thanks for your quick reply,

After git pull  and  another long  compile time passed, the message still show me that : 

[+] mesalockiso: installing rootfs
tar (child): build/out/minit.tar.xz: Cannot open: No such file or directory

I want dig into the error messages but the compiler script output show nothing about minit .


BTW, the generated tar files as below:

gcc-libs.tar.xz
ripgrep.tar.xz
linux.tar.xz
syslinux.tar.xz
tzdata.tar.xz
micro.tar.xz
glibc.tar.xz
busybox.tar.xz
filesystem.tar.xz
init.tar.xz
tokei.tar.xz
ion-shell.tar.xz
fd-find.tar.xz
exa.tar.xz

thanks .

**Comment by mssun** [comment]
@cloudtrends sorry, I should tell you to update the submodule using this command: `git submodule update --recursive`

**Comment by mssun** [comment]
After that, you don't have to rebuild the whole project. Just make the missing packages by `./mkpkg <package_name>`.

**Comment by cloudtrends** [comment]
@mssun   thanks you very much ,  my first mesalock-linux iso is build out!

$ ls -lth  build
total 62M
62M 12月  5 07:25 mesalock-linux.iso

**Comment by mssun** [comment]
Great! Thanks for your interests.
